### PR TITLE
Add public inits and allow mutating diff elements

### PR DESCRIPTION
**Pull request by p4checo**
On some scenarios, it's useful to be able to create or mutate a `Diff`
instance (or another variant), for example:
  - exclude some changes from the calculated diff
  - manually build our own diff, for simple scenarios

Since `init(elements:)` is auto generated by the compiler, it gets the
default `internal` visibility, meaning it's not accessible outside
`Differ`'s module. Adding a `public init(elements:)` enables this usage.

Additional `ExpressibleByArrayLiteral` conformance was added, to make
the creation of custom instances even easier.

The `elements` property was made `var`, because it enables mutating the
`struct` when the instance is itself mutable.

The following changes was applied only to `Diff`, `NestedDiff` and
`NestedExtendedDiff`. `ExtendedDiff` was not modified because it
contains additional properties (i.e. `source`, `sourceIndex`,
`reorderedIndex` and `moveIndices`) which are used in `ExtendedPatch` 
operations.

### CODE REVIEW

**Comment by p4checo** [comment]
didn't fix Unit Tests, because then I would break them again for Swift 4.1 😆

**Comment by p4checo** [comment]
Cool! No worries! 👍 
Do you want me to add anything, or can we merge this? 😇 
Thanks!

**Comment by tonyarnold** [comment]
I was trying to do the Swift 4.1 migration first, but the unit tests are bung - if you have any ideas, please have a look at #20!

**Comment by p4checo** [comment]
Ok, that makes sense, sorry for rushing things 😅 
I'll try to take a look at the migration 😉

**Comment by tonyarnold** [comment]
No need to apologise, I'm keen to release an update today if I can get these tests running.

**Comment by p4checo** [comment]
That's great news! I don't know if I'll be able to dedicate much time to this today, because it's a bit late on my timezone (1:25 am), but tomorrow I can catch up on this.

**Pull request merged**
